.TH minisphere 1 "1 Feb 2016" "minisphere 3.0.0"
.SH NAME
minisphere - JavaScript game engine
.SH SYNOPSIS
sphere [options] <path>
.SH DESCRIPTION
minisphere is general-purpose game engine which uses JavaScript to implement
game logic.
.SH OPTIONS
.IP --debug
waits for the SSJ debugger to attach before beginning game execution
.SH AUTHOR
Bruce Pascoe <fatcerberus@icloud.com>
