.TH sphere 1 "2016-02-01" "minisphere 3.0.0" "...the talking is coming from INSIDE the hunger-pig!"
.SH NAME
minisphere - Sphere-compatible JavaScript game engine
.SH SYNOPSIS
sphere [options] <path>
.SH DESCRIPTION
minisphere is a general-purpose game engine which uses JavaScript for game
coding. It is mostly compatible with the Sphere game engine developed by
Chad Austin, but is not a fork of that engine. minisphere was written from the
ground up in C and is officially supported on both Windows and Linux platforms.
As it is designed to be compatible, the command to invoke the engine is
.B
sphere
.SH OPTIONS
.IP --debug
Waits for ssj(1) to attach before beginning game execution.
.IP --log <n>
Sets the engine's verbosity level.
.SH AUTHOR
Bruce Pascoe <fatcerberus@icloud.com>
