.TH MINISPHERE 1 "2018-05-05" "miniSphere-5.0.2" "miniSphere JS Game Engine"
.SH NAME
minisphere \- lightweight JavaScript-powered game engine
.SH SYNOPSIS
.nh
.na
.TP 11
.B minisphere
[\fB\-\-fullscreen\fR | \fB\-\-windowed\fR]
[\fB\-\-frameskip \fImaxframes\fR]
.RI [ spkfile ]
.ad
.hy
.SH DESCRIPTION
miniSphere is a general-purpose game engine which uses JavaScript for game coding.
It is a mostly compatible reimplementation of the Sphere game engine developed by Chad Austin (it is not a fork), boasting better performance and several new features and enhancements.
.P
When run with no arguments, miniSphere will launch with a menu allowing you to choose from a list of installed Sphere games.
You can also pass the name of an
.I .spk
(Sphere game PacKage) file on the command line to launch that game directly.
.P
When developing a game,
.BR spherun (1)
should be used to launch the engine instead of
.BR minisphere (1).
This enables a number of features useful during game development, such as debugging using
.BR ssj (1)
and engine logging via the
.B \-\-verbose
option.
.SH OPTIONS
.B Important note:
.br
Unrecognized options to the
.BR minisphere (1)
command will be silently ignored.
.P
.IP \fB\-\-fullscreen
Starts miniSphere in fullscreen mode. This is the default when starting the engine using the
.BR minisphere (1)
command.
.IP \fB\-\-windowed
Starts miniSphere in windowed mode.
.IP \fB\-\-frameskip
miniSphere skips rendering frames when it can't keep up with a game's requested framerate.
To ensure games remain playable, no more than 5 consecutive frames will be skipped by default.
This option may be used to change the maximum to deal with slow machines; note, however, that games can override the value you provide.
.SH BUGS
Report any bugs found in miniSphere or the miniSphere GDK tools to:
.br
.I Bruce Pascoe <fatcerberus@icloud.com>
.P
.B While not bugs per se, there are some known limitations in miniSphere compared to Sphere:
.IP \(bu 3
Sphere games using mp3 audio will not run in miniSphere.
Due to licensing restrictions, there is no built-in support for mp3.
All known FOSS mp3 decoders are GPL, while miniSphere is licensed under 3-clause BSD.
It is therefore impossible to support mp3 out-of-the-box unless miniSphere is relicensed under the GPL.
.SH "SEE ALSO"
.BR spherun (1),
.BR cell (1),
.BR ssj (1)
