msphere_defines = [
	"DUK_OPT_HAVE_CUSTOM_H"
]

msphere_sources = [
	Object("duktape", "#/src/shared/duktape.c"),
	Object("dyad", "#/src/shared/dyad.c"),
	Object("mt19937ar", "#/src/shared/mt19937ar.c"),
	Object("lstring", "#/src/shared/lstring.c"),
	Object("path", "#/src/shared/path.c"),
	Object("unicode", "#/src/shared/unicode.c"),
	Object("vector", "#/src/shared/vector.c"),
	"main.c",
	"animation.c",
	"api.c",
	"async.c",
	"audialis.c",
	"atlas.c",
	"bytearray.c",
	"color.c",
	"console.c",
	"debugger.c",
	"file.c",
	"font.c",
	"galileo.c",
	"geometry.c",
	"image.c",
	"input.c",
	"logger.c",
	"map_engine.c",
	"obsmap.c",
	"persons.c",
	"primitives.c",
	"rng.c",
	"script.c",
	"shader.c",
	"sockets.c",
	"spherefs.c",
	"spk.c",
	"spriteset.c",
	"surface.c",
	"tileset.c",
	"utility.c",
	"windowstyle.c",
]

msphere_libs = [
	"allegro_acodec",
	"allegro_audio",
	"allegro_color",
	"allegro_dialog",
	"allegro_image",
	"allegro_main",
	"allegro_memfile",
	"allegro_primitives",
	"allegro",
	"mng",
	"z",
	"m",
]

minisphere = Program("msphere",
	msphere_sources,
	CPPPATH = [ ".", "#/src/shared" ],
	CPPDEFINES = msphere_defines,
	LIBS = msphere_libs)
Return("minisphere")

