cell_sources = [
	Object("duktape", "#/src/shared/duktape.c"),
	Object("path", "#/src/shared/path.c"),
	Object("vector", "#/src/shared/vector.c"),
	"main.c",
	"assets.c",
	"build.c",
	"spk_writer.c",
	"utility.c",
]

cell_libs = [
	"z",
	"m"
]

cell = Program("cell",
	cell_sources,
	CPPPATH = "#/src/shared",
	LIBS = cell_libs)
Return("cell")

