cell_sources = [
	Object("duktape", "../msphere/duktape.c"),
	Object("path", "../msphere/path.c"),
	Object("vector", "../msphere/vector.c"),
	
	"assets.c",
	"build.c",
	"spk_writer.c",
	"utility.c",
	"main.c"
]

cell_libs = [
	"z",
	"m"
]

cell = Program("cell",
	cell_sources, CPPPATH = "#/src",
	LIBS = cell_libs)
Return("cell")
