msphere_sources = [
    "duktape.c",
    "dyad.c",
    "api.c",
    "bytearray.c",
    "color.c",
    "file.c",
    "font.c",
    "geometry.c",
    "image.c",
    "input.c",
    "logger.c",
    "lstring.c",
    "main.c",
    "map_engine.c",
    "obsmap.c",
    "persons.c",
    "primitives.c",
    "rawfile.c",
    "script.c",
    "sockets.c",
    "sound.c",
    "spriteset.c",
    "surface.c",
    "tileset.c",
    "windowstyle.c"

]

msphere_libs = [
    "allegro",
    "allegro_audio",
    "allegro_acodec",
    "allegro_color",
    "allegro_dialog",
    "allegro_font",
    "allegro_image",
    "allegro_primitives",
    "allegro_ttf",
    "allegro_main",
    "m"
]

minisphere = Program("msphere", msphere_files, LIBS = msphere_libs)

Return("minisphere")
