#ifndef MINISPHERE__VERSION_H__INCLUDED
#define MINISPHERE__VERSION_H__INCLUDED

#define ENGINE_NAME   "miniSphere"
#define COMPILER_NAME "Cell"
#define DEBUGGER_NAME "SSJ"
#define PREPTOOL_NAME "Majin"

#define VERSION_NAME  "4.5.10"

#endif // MINISPHERE__VERSION_H__INCLUDED
