#ifndef MINISPHERE__VERSION_H__INCLUDED
#define MINISPHERE__VERSION_H__INCLUDED

#define VERSION_NAME "3.0.6"
#define PRODUCT_NAME "minisphere " VERSION_NAME

#endif // MINISPHERE__VERSION_H__INCLUDED
