.TH SPHERUN 1 "2016-02-03" "minisphere-3.0a0" "minisphere Game Development Kit"
.SH NAME
spherun \- run Sphere game in a dev-friendly environment
.SH SYNOPSIS
.nh
.na
.TP 8
.B spherun
[\fB\-\-debug\fR]
[\fB\-\-fullscreen\fR | \fB\-\-window\fR]
[\fB\-\-frameskip \fImaxframes\fR]
[\fB\-\-no\-throttle]
[\fB\-\-verbose \fIlevel\fR]
.I gamefile
.ad
.hy
.SH DESCRIPTION
minisphere is a general-purpose game engine which uses JavaScript for game coding.
It is mostly compatible with the Sphere game engine developed by Chad Austin, but is not a fork of that engine.

Normally, minisphere is launched via the command
.BR minisphere (1).
When the engine is started that way, all debugging and logging features are disabled to maximize game performance.
Thus,
.BR spherun (1)
is the preferred way to invoke the engine while developing a game.
.SH OPTIONS
.IP \fB\-\-fullscreen
Starts the engine in fullscreen mode. This option is ignored if
.B \-\-debug
is used (see below).
.IP \fB\-\-window
Starts the engine in windowed mode. This is the default.
.TP
.BR \-d ", " \-\-debug
Instructs minisphere to wait for the
.BR ssj (1)
debugger to attach before beginning game execution.
If no debugger attaches within 30 seconds, minisphere will exit.
.TP
.BR \-v ", " \-\-verbose
Sets the engine's diagnostic verbosity level.
This lets you to see under the hood at the engine's internal operation, which can often illuminate bugs in your game's logic.
If this option is not given, minisphere will only print its version header and whatever output is generated by the game being executed.
.IP \fB\-\-no-throttle
Disable CPU idle throttling.
minisphere tries to minimize its CPU usage, which can sometimes trigger subtle game bugs.
Use this option to disable it temporarily as a debugging aid.
.IP \fB\-\-frameskip <n>
minisphere skips rendering frames when it can't keep up with a game's requested framerate.
To ensure games remain playable, no more than 5 consecutive frames will be skipped by default.
Use this option to change the maximum; note, however, that games can override the value you provide.
.IP \fB\-\-version
Displays the version number of this copy of minisphere along with the version numbers of any libraries it depends on.
.SH BUGS
Report any bugs found in minisphere or the GDK tools to:
.br
.I Bruce Pascoe <fatcerberus@icloud.com>
.PP
.B While not bugs per se, there are some known limitations in minisphere 3.0 compared to Sphere:
.IP \(bu
Due to licensing restrictions, there is no built-in support in minisphere for mp3 audio.
All known FOSS mp3 decoders are GPL, while minisphere is licensed under 3-clause BSD.
It is therefore impossible to support mp3 out-of-the-box unless minisphere is relicensed under the GPL, which I won't do.
.IP \(bu
Compared to Sphere, minisphere is stricter about arguments to engine APIs and will complain if, e.g., a string is passed to a function expecting an integer.
For existing codebases, code changes may be required to make the game work properly under minisphere.
.SH "SEE ALSO"
.BR cell (1),
.BR ssj (1)
