.TH SSJ 1 "2016-02-03" "minisphere-3.0a0" "minisphere Game Development Kit"
.SH NAME
ssj \- a JavaScript console debugger for minisphere
.SH SYNOPSIS
.nh
.na
.TP
.B ssj
.RB [ \-\-pause ]
.RB [ \-\-attach " | "
.IR gamefile ]
.ad
.hy
.SH DESCRIPTION
When used in combination with minisphere, SSJ allows you step through a game's code and track its state as it executes.
In this regard it is similar in purpose to other console debuggers such as GDB.
.SH BUGS
Report any bugs found in minisphere or the GDK tools to:
.br
.B Bruce Pascoe <fatcerberus@icloud.com>
.SH SEE ALSO
.BR sphere (1),
.BR cell (1)
