msphere_sources = [
	"duktape.c",
	"dyad.c",
	"animation.c",
	"api.c",
	"async.c",
	"atlas.c",
	"bytearray.c",
	"color.c",
	"console.c",
	"file.c",
	"font.c",
	"galileo.c",
	"geometry.c",
	"image.c",
	"input.c",
	"logger.c",
	"lstring.c",
	"main.c",
	"map_engine.c",
	"mt19937ar.c",
	"obsmap.c",
	"particles.c",
	"persons.c",
	"primitives.c",
	"rng.c",
	"script.c",
	"shader.c",
	"sockets.c",
	"sound.c",
	"spherefs.c",
	"spk.c",
	"spriteset.c",
	"surface.c",
	"tileset.c",
	"unicode.c",
	"utility.c",
	"vector.c",
	"windowstyle.c"
]

msphere_libs = [
	"allegro_acodec",
	"allegro_audio",
	"allegro_color",
	"allegro_dialog",
	"allegro_image",
	"allegro_memfile",
	"allegro_primitives",
	"allegro",
	"mng",
	"jpeg",
	"z",
	"m"
]

minisphere = Program("msphere", msphere_sources, LIBS = msphere_libs)

Return("minisphere")
