#ifndef MINISPHERE__VERSION_H__INCLUDED
#define MINISPHERE__VERSION_H__INCLUDED

#define ENGINE_NAME   "minisphere 2.1.3"
#define COMPILER_NAME "Cell 2.1.3"

#endif // MINISPHERE__VERSION_H__INCLUDED
