ssj_sources = [
	Object("dyad", "../msphere/dyad.c"),
	Object("lstring", "../msphere/lstring.c"),
	Object("path", "../msphere/path.c"),
	Object("unicode", "../msphere/unicode.c"),
	Object("vector", "../msphere/vector.c"),
	"main.c",
	"remote.c",
	"session.c",
]

ssj_libs = [
	"m"
]

ssj = Program("ssj",
	ssj_sources, CPPPATH = "#/src",
	LIBS = ssj_libs)
Return("ssj")
