ssj_sources = [
	Object("dyad", "../msphere/dyad.c"),
	Object("path", "../msphere/path.c"),
	Object("vector", "../msphere/vector.c"),
	"main.c",
	"client.c",
]

ssj_libs = [
	"m"
]

ssj = Program("ssj",
	ssj_sources, CPPPATH = "#/src",
	LIBS = ssj_libs)
Return("ssj")
